package com.luotf.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
@JsonIgnoreProperties({ "handler","hibernateLazyInitializer" })
public class Comment {
    /**  */
    private Integer id;

    /** 评论内容 */
    private String content;

    /** 随机图片(0-5)之间 */
    private Integer image;

    /** 评论邮箱 */
    private String useremail;

    /** 赞同数 */
    private Integer agree;

    /** 不赞同量 */
    private Integer disagree;

    /** 评论时间 */
    private Date commenttime;

    /** 审核 */
    private Integer status;

    /**  */
    private Integer blogId;

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.image
     *
     * @return the value of t_comment.image
     *
     * @mbggenerated
     */
    public Integer getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.image
     *
     * @param image the value for t_comment.image
     *
     * @mbggenerated
     */
    public void setImage(Integer image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.userEmail
     *
     * @return the value of t_comment.userEmail
     *
     * @mbggenerated
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.userEmail
     *
     * @param useremail the value for t_comment.userEmail
     *
     * @mbggenerated
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.agree
     *
     * @return the value of t_comment.agree
     *
     * @mbggenerated
     */
    public Integer getAgree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.agree
     *
     * @param agree the value for t_comment.agree
     *
     * @mbggenerated
     */
    public void setAgree(Integer agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.disagree
     *
     * @return the value of t_comment.disagree
     *
     * @mbggenerated
     */
    public Integer getDisagree() {
        return disagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.disagree
     *
     * @param disagree the value for t_comment.disagree
     *
     * @mbggenerated
     */
    public void setDisagree(Integer disagree) {
        this.disagree = disagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentTime
     *
     * @return the value of t_comment.commentTime
     *
     * @mbggenerated
     */
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentTime
     *
     * @param commenttime the value for t_comment.commentTime
     *
     * @mbggenerated
     */
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.status
     *
     * @return the value of t_comment.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.status
     *
     * @param status the value for t_comment.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.blog_id
     *
     * @return the value of t_comment.blog_id
     *
     * @mbggenerated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.blog_id
     *
     * @param blogId the value for t_comment.blog_id
     *
     * @mbggenerated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }
}